---
language: python
services: docker

env:
  global:
    - ROLE_NAME: administrators
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos6
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604

install:
  # Install test dependencies.
  - pip install molecule docker # Compatibility issue between testinfra and molecule and Ansible
  - pip install molecule==2.19 ansible==2.7.11

script:
  # Run tests.
  - molecule test

notifications:
webhooks: https://galaxy.ansible.com/api/v1/notifications/
