---
- name: administrative user
  user:
    name: "{{ item }}"
  loop: "{{ administrators_names }}"

- name: Copy SSH keys to administrative user
  authorized_key:
    user: "{{ item.username }}"
    state: present
    key: "{{ lookup('file', item.key) }}"
  loop: "{{ administrators_keys }}"

- name: sudoer
  template:
    src: etc/sudoers.d/template
    dest: "/etc/sudoers.d/{{item}}"
  loop: "{{ administrators_names }}"
