---
- name: Administrative user
  user:
    name: "{{ item.name  }}"
    shell: "{{ administrators_default_shell }}"
  loop: "{{ administrators_names }}"
  when: "item.active == true"

- name: Copy SSH keys to administrative user
  authorized_key:
    user: "{{ item.username }}"
    state: present
    key: "{{ lookup('file', item.key) }}"
  loop: "{{ administrators_keys }}"
  when: "item.active == true"

- name: Sudoer
  template:
    src: etc/sudoers.d/template
    dest: "/etc/sudoers.d/{{ item.name }}"
  loop: "{{ administrators_names }}"
  when: "item.active == true"

- name: Remove user
  user:
    name: "{{ item.name }}"
    shell: "{{ administrators_default_shell }}"
    state: absent
    remove: yes
  loop: "{{ administrators_names }}"
  when: "item.active == false"

