---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: Include acme.my_new_role
      ansible.builtin.include_role:
        name: acme.molecule_reference_role
  post_tasks:
    - name: Ensure user exists
      ansible.builtin.command: grep admin /etc/passwd
      register: result
      until: result.failed == false
      retries: 3
      delay: 1
